import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { compose, contextualTrackGenerationSchema } from "../lib/domain.ts";
import { AceStepMusicProvider, ElevenLabsMusicProvider, MiniMaxMusicProvider, MockMusicProvider, createProvider } from "../lib/providers.ts";
import { InlineTestGenerationQueue } from "../lib/generation-queue.ts";
import { validateElevenLabsPolicy } from "../lib/provider-policy.ts";
test("generation status GET is observational only",async()=>{const source=await readFile(new URL("../app/api/generations/[id]/route.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/\.generate\(|orchestrator\.process|\.put\(/);assert.match(source,/select j\.id/)});
test("Worker routes pass the PostgreSQL binding through authentication",async()=>{const files=["auth/register","auth/login","auth/logout","auth/session","generations","generations/[id]","audio/[id]","songs/[id]"];for(const file of files){const source=await readFile(new URL(`../app/api/${file}/route.ts`,import.meta.url),"utf8");assert.match(source,/env|bindings/);assert.match(source,/DATABASE_URL/)}});
test("local queue executes without any status read",async()=>{let delivered="";const queue=new InlineTestGenerationQueue(async id=>{delivered=id});await queue.enqueue("job-1");await new Promise(resolve=>setTimeout(resolve,0));assert.equal(delivered,"job-1")});
test("mock provider supports one aligned master and six aligned assets",async()=>{const input={prompt:"warm reflective soul performance",durationSeconds:1,outputMode:"MULTI_ASSET" as const,lyrics:"",instrumental:false},plan=compose(input),provider=new MockMusicProvider(),base={jobId:"j",userId:"u",songId:"s",versionId:"v",compositionPlan:plan,seed:42};const multi=await provider.generate({...base,outputMode:"MULTI_ASSET"});assert.equal(multi.assets.length,6);assert.equal(multi.assets.filter(a=>a.role==="MASTER"&&a.isPrimary).length,1);assert.ok(multi.assets.every(a=>a.metadata.durationSeconds===1));const single=await provider.generate({...base,outputMode:"MASTER_ONLY"});assert.deepEqual(single.assets.map(a=>a.role),["MASTER"])});
test("PostgreSQL schema encodes idempotency and normalized assets",async()=>{const migration=await readFile(new URL("../drizzle-pg/0000_condemned_silhouette.sql",import.meta.url),"utf8");assert.match(migration,/CREATE TABLE "version_assets"/);assert.match(migration,/jobs_user_idempotency_unique/);assert.match(migration,/versions_job_unique/);assert.match(migration,/parent_version_id/)});
test("contextual track lineage is relational",async()=>{const migration=await readFile(new URL("../drizzle-pg/0004_freezing_lester.sql",import.meta.url),"utf8");assert.match(migration,/track_generation_method/);assert.match(migration,/source_asset_id/);assert.match(migration,/LEGO_CONTEXTUAL/);assert.match(migration,/version_assets_source_asset_id_audio_assets_id_fk/)});
test("ACE-Step selection stays behind the provider-neutral gateway",()=>{const provider=createProvider("acestep",{aiServiceBaseUrl:"http://127.0.0.1:8000",aceStepModel:"acestep-v15-turbo"});assert.ok(provider instanceof AceStepMusicProvider);assert.equal(provider.name,"acestep");assert.equal(provider.model,"acestep-v15-turbo");assert.equal(provider.capabilities().nativeMultitrack,false);assert.equal(provider.capabilities().masterGeneration,"EXPERIMENTAL");assert.equal(provider.capabilities().contextualRegeneration,"EXPERIMENTAL");assert.equal(provider.capabilities().sourceSeparation,"UNAVAILABLE")});

test("MiniMax selection is an experimental local master provider",()=>{assert.throws(()=>createProvider("minimax"),/GENERATION_PROVIDER_UNAVAILABLE/);const provider=createProvider("minimax",{aiServiceBaseUrl:"http://127.0.0.1:8000",minimaxModel:"MiniMax-Music3-mxfp8"});assert.ok(provider instanceof MiniMaxMusicProvider);assert.equal(provider.name,"minimax");assert.equal(provider.model,"MiniMax-Music3-mxfp8");assert.equal(provider.capabilities().masterGeneration,"EXPERIMENTAL");assert.equal(provider.capabilities().nativeMultitrack,false)});

test("Eleven Music selection is experimental and requires its dedicated key",()=>{assert.throws(()=>createProvider("elevenlabs"),/GENERATION_PROVIDER_UNAVAILABLE/);const provider=createProvider("elevenlabs",{elevenLabsApiKey:"test-key"});assert.ok(provider instanceof ElevenLabsMusicProvider);assert.equal(provider.name,"elevenlabs");assert.equal(provider.model,"music_v2");assert.equal(provider.capabilities().masterGeneration,"EXPERIMENTAL");assert.equal(provider.capabilities().nativeMultitrack,false)});

test("Eleven Music sends a master-only v2 request and normalizes binary audio",async()=>{const original=globalThis.fetch,input={prompt:"warm reflective soul performance",durationSeconds:12,outputMode:"MASTER_ONLY" as const,lyrics:"Hold on to the light",instrumental:false},plan=compose(input);let sent:RequestInit|undefined;globalThis.fetch=async(url,init)=>{assert.equal(url,"https://api.elevenlabs.io/v1/music?output_format=mp3_48000_192");sent=init;return new Response(new Uint8Array([0x49,0x44,0x33]),{headers:{"content-type":"audio/mpeg","song-id":"song-123"}})};try{const provider=new ElevenLabsMusicProvider("secret-key"),result=await provider.generate({jobId:"j",userId:"u",songId:"s",versionId:"v",compositionPlan:plan,lyrics:input.lyrics,seed:42,outputMode:"MASTER_ONLY"});assert.equal((sent?.headers as Record<string,string>)["xi-api-key"],"secret-key");const body=JSON.parse(String(sent?.body));assert.equal(body.model_id,"music_v2");assert.equal(body.music_length_ms,12000);assert.match(body.prompt,/Hold on to the light/);assert.equal(result.assets[0].metadata.mimeType,"audio/mpeg");assert.deepEqual(result.assets[0].audio.bytes,new Uint8Array([0x49,0x44,0x33]));assert.equal(result.assets[0].providerMetadata?.songId,"song-123")}finally{globalThis.fetch=original}});
test("Eleven Music normalizes copyrighted prompt rejection without exposing provider details",async()=>{const original=globalThis.fetch,input={prompt:"warm reflective soul performance",durationSeconds:12,outputMode:"MASTER_ONLY" as const,lyrics:"",instrumental:true},plan=compose(input);globalThis.fetch=async()=>Response.json({detail:{status:"bad_prompt",data:{prompt_suggestion:"provider text must stay private"}}},{status:422});try{const provider=new ElevenLabsMusicProvider("secret-key");await assert.rejects(()=>provider.generate({jobId:"j",userId:"u",songId:"s",versionId:"v",compositionPlan:plan,seed:42,outputMode:"MASTER_ONLY"}),error=>error instanceof Error&&error.message==="PROVIDER_PROMPT_REJECTED")}finally{globalThis.fetch=original}});
test("Eleven Music UI includes attribution, format metadata, and sanitized policy guidance",async()=>{const[studio,route]=await Promise.all([readFile(new URL("../app/studio-app.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/generations/route.ts",import.meta.url),"utf8")]);assert.match(studio,/Powered by ElevenLabs/);assert.match(route,/restricted copyrighted or artist-identifying material/);assert.match(route,/provider:r\.provider/);assert.match(route,/errorMessage:r\.errorMessage/)});
test("Eleven Music requires rights confirmation and blocks imitation phrases before generation",()=>{const allowed={prompt:"original warm soul with restrained drums",lyrics:"my original lyric",providerPolicyAccepted:true};assert.doesNotThrow(()=>validateElevenLabsPolicy(allowed));assert.throws(()=>validateElevenLabsPolicy({...allowed,providerPolicyAccepted:false}),/PROVIDER_POLICY_ACCEPTANCE_REQUIRED/);for(const prompt of["sounds like a famous singer","in the style of a band","mimic this artist"]){assert.throws(()=>validateElevenLabsPolicy({...allowed,prompt}),/PROVIDER_PROMPT_REJECTED/)}});
test("Eleven Music disclosure is sent with generation requests",async()=>{const source=await readFile(new URL("../app/studio-app.tsx",import.meta.url),"utf8");assert.match(source,/I have rights to this prompt and its lyrics/);assert.match(source,/sent to ElevenLabs/);assert.match(source,/providerPolicyAccepted/)});
test("contextual track requests reject invented drum subtargets",()=>{assert.throws(()=>contextualTrackGenerationSchema.parse({sourceAssetId:crypto.randomUUID(),targetInstrumentGroup:"kick",seed:1}),/Invalid option/);assert.equal(contextualTrackGenerationSchema.parse({sourceAssetId:crypto.randomUUID(),targetInstrumentGroup:"drums",seed:1}).targetInstrumentGroup,"drums")});
test("Lego results normalize to contextual native tracks",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({assets:[{assetKey:"lego-bass",role:"NATIVE_TRACK",instrument:"bass",instrumentGroup:"bass",provenance:"GENERATED_NATIVE",isPrimary:false,sortOrder:0,audio:{base64:"UklGRg=="},metadata:{mimeType:"audio/wav",codec:"pcm_s16le",sampleRate:48000,bitDepth:16,channels:2,durationSeconds:8,waveformData:[]},providerMetadata:{generationMethod:"LEGO_CONTEXTUAL",sourceAssetId:"00000000-0000-4000-8000-000000000001"}}]});try{const provider=new AceStepMusicProvider("http://gateway"),result=await provider.generateContextualTrack!({jobId:"j",userId:"u",songId:"s",versionId:"v",sourceAssetId:"00000000-0000-4000-8000-000000000001",targetInstrumentGroup:"bass",seed:1,caption:"warm",sourceAudio:new Uint8Array([1]),sourceMimeType:"audio/wav"});assert.equal(result.assets[0].role,"NATIVE_TRACK");assert.equal(result.assets[0].provenance,"GENERATED_NATIVE");assert.equal(result.assets[0].providerMetadata?.generationMethod,"LEGO_CONTEXTUAL");assert.ok(result.assets[0].audio.bytes)}finally{globalThis.fetch=original}});
