/* eslint-disable jsx-a11y/media-has-caption -- generated instrumental audio has no dialogue to caption */
"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

type Status="QUEUED"|"PREPARING"|"GENERATING"|"POST_PROCESSING"|"UPLOADING"|"COMPLETE"|"FAILED"|"CANCELLED";
type Song={id:string;title:string;prompt:string;createdAt:string;version:number;duration:number;bpm:number;musicalKey:string;genre:string;status:Status;progress:number;waveform:number[];seed:number;audioUrl?:string};
type User={id:string;email:string;displayName:string};
const paths:Record<string,string>={create:"M12 3v18M3 12h18",library:"M4 5v14M9 5v14M14 7v12M19 4v15",play:"m9 7 8 5-8 5V7Z",pause:"M9 7v10M15 7v10",heart:"M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l8.9 8.6 8.8-8.6a5.5 5.5 0 0 0 1.1-8.9Z",more:"M5 12h.01M12 12h.01M19 12h.01",spark:"m12 3-1.4 4.2L7 9l3.6 1.8L12 15l1.4-4.2L17 9l-3.6-1.8L12 3Z",search:"m21 21-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z",skip:"m6 6 8 6-8 6V6Zm10 0v12",volume:"M11 5 6 9H2v6h4l5 4V5Zm4.5 3.5a5 5 0 0 1 0 7",chevron:"m9 18 6-6-6-6",download:"M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"};
const labels:Record<Status,string>={QUEUED:"Queued",PREPARING:"Preparing composition",GENERATING:"Generating audio",POST_PROCESSING:"Analyzing mix",UPLOADING:"Saving master",COMPLETE:"Ready",FAILED:"Generation failed",CANCELLED:"Cancelled"};
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>}
function Wave({data,progress=0,compact=false,onSeek}:{data:number[];progress?:number;compact?:boolean;onSeek?:(n:number)=>void}){return <button className={`waveform ${compact?"compact":""}`} aria-label="Seek in song" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek?.((e.clientX-r.left)/r.width)}}>{data.map((p,i)=><i key={i} className={i/data.length<=progress?"played":""} style={{height:`${Math.max(10,p*100).toFixed(2)}%`}}/>)}</button>}

function AuthGate({onAuthenticated}:{onAuthenticated:(u:User)=>void}){
 const[register,setRegister]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget),body={displayName:String(form.get("displayName")||""),email:String(form.get("email")||""),password:String(form.get("password")||"")};try{const res=await fetch(`/api/auth/${register?"register":"login"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await res.json() as {user?:User;error?:{message:string}};if(!res.ok||!data.user)throw new Error(data.error?.message||"Could not sign in.");onAuthenticated(data.user)}catch(err){setError(err instanceof Error?err.message:"Could not sign in.")}finally{setBusy(false)}}
 return <div className="auth-screen"><section><div className="auth-brand"><span>dz</span><p>DOZI MUSIC STUDIO</p></div><h1>{register?"Create your studio":"Welcome back"}</h1><p>Your songs, versions, and masters stay attached to your private Dozi account—never a ChatGPT login.</p><form onSubmit={submit}>{register&&<label>Display name<input name="displayName" autoComplete="name" required maxLength={80}/></label>}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={register?"new-password":"current-password"} required minLength={10}/></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="generate" disabled={busy}>{busy?"Please wait…":register?"Create account":"Sign in"}</button></form><button className="auth-switch" onClick={()=>{setRegister(v=>!v);setError("")}}>{register?"Already have an account? Sign in":"New to Dozi? Create an account"}</button></section></div>
}

export default function StudioApp(){
 const[user,setUser]=useState<User|null|undefined>(undefined),[view,setView]=useState<"create"|"library">("create"),[mode,setMode]=useState<"Simple"|"Advanced">("Simple"),[prompt,setPrompt]=useState("Warm neo-soul song about finding purpose later in life"),[instrumental,setInstrumental]=useState(false),[lyrics,setLyrics]=useState(""),[songs,setSongs]=useState<Song[]>([]),[active,setActive]=useState<Song|null>(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[search,setSearch]=useState(""),[blueprint,setBlueprint]=useState(true),[submitting,setSubmitting]=useState(false),[notice,setNotice]=useState("");
 const audio=useRef<HTMLAudioElement|null>(null),plan=useMemo(()=>({genre:prompt.toLowerCase().includes("soul")?"Neo-soul":"Alternative pop",bpm:prompt.toLowerCase().includes("slow")?68:76,key:"F♯ minor",mood:prompt.toLowerCase().includes("warm")?"Warm · Reflective":"Intimate · Hopeful"}),[prompt]);
 const loadSongs=useCallback(async()=>{const res=await fetch("/api/generations",{cache:"no-store"});if(res.ok){const data=await res.json() as {songs:Song[]};setSongs(data.songs)}},[]);
 useEffect(()=>{fetch("/api/auth/session").then(r=>r.json()).then(async(d:{user:User|null})=>{setUser(d.user);if(d.user)await loadSongs()}).catch(()=>setUser(null))},[loadSongs]);
 useEffect(()=>{const pending=songs.filter(s=>!["COMPLETE","FAILED","CANCELLED"].includes(s.status));if(!pending.length)return;const timer=setInterval(async()=>{const updates=await Promise.all(pending.map(s=>fetch(`/api/generations/${s.id}`,{cache:"no-store"}).then(r=>r.json()).then((d:{song:Song})=>d.song)));setSongs(current=>current.map(s=>updates.find(u=>u.id===s.id)||s))},1000);return()=>clearInterval(timer)},[songs]);
 useEffect(()=>{const el=audio.current;if(!el)return;if(playing){void el.play().catch(()=>setPlaying(false))}else{el.pause()}},[playing,active]);
 const fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,"0")}`;
 function play(song:Song){if(!song.audioUrl)return;if(active?.id===song.id)setPlaying(v=>!v);else{setActive(song);setTime(0);setPlaying(true)}}
 async function generate(){if(!prompt.trim()||submitting)return;setSubmitting(true);setNotice("");try{const res=await fetch("/api/generations",{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({prompt,lyrics,instrumental,genre:plan.genre,bpm:plan.bpm,key:"F#",durationSeconds:12})}),data=await res.json() as {song?:Song;error?:{message:string}};if(!res.ok||!data.song)throw new Error(data.error?.message||"Generation could not start.");setSongs(x=>[data.song as Song,...x])}catch(err){setNotice(err instanceof Error?err.message:"Generation could not start.")}finally{setSubmitting(false)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setUser(null);setSongs([]);setActive(null);setPlaying(false)}
 if(user===undefined)return <div className="boot"><span>dz</span><p>Opening your studio…</p></div>;if(!user)return <AuthGate onAuthenticated={setUser}/>;
 const filtered=songs.filter(s=>(s.title+s.prompt).toLowerCase().includes(search.toLowerCase()));
 return <div className="app-shell"><aside className="rail"><div className="brand"><span>dz</span></div><nav aria-label="Main navigation"><button className={view==="create"?"active":""} onClick={()=>setView("create")}><Icon name="create"/><span>Create</span></button><button className={view==="library"?"active":""} onClick={()=>setView("library")}><Icon name="library"/><span>Library</span></button></nav><div className="rail-bottom"><button className="avatar" aria-label="Sign out" title={`Sign out ${user.email}`} onClick={logout}>{user.displayName.slice(0,2).toUpperCase()}</button></div></aside><main><header className="topbar"><div><p>DOZI MUSIC STUDIO</p><h1>{view==="create"?"Create":"Your library"}</h1></div><div className="provider"><i/>Mock engine <span>Server ready</span></div></header>
 {view==="create"?<div className="workspace"><section className="composer"><div className="mode-tabs">{(["Simple","Advanced"] as const).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m)}>{m}</button>)}</div><label className="field-label" htmlFor="idea">SONG IDEA <span>{prompt.length}/500</span></label><textarea id="idea" value={prompt} maxLength={500} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the song you want to make…"/><div className="toggle-row"><div><strong>Instrumental</strong><small>Create without vocals</small></div><button role="switch" aria-checked={instrumental} className={`switch ${instrumental?"on":""}`} onClick={()=>setInstrumental(v=>!v)}><i/></button></div>{!instrumental&&<><div className="section-head"><span>LYRICS</span><button onClick={()=>setLyrics("[Verse 1]\nThe road got quiet, but I kept the light\n\n[Chorus]\nPurpose finds us in its own sweet time")}>Generate for me <Icon name="spark"/></button></div><textarea className="lyrics" value={lyrics} onChange={e=>setLyrics(e.target.value)} placeholder="Leave blank and Dozi will write lyrics, or add your own…"/></>}{mode==="Advanced"&&<div className="advanced-grid"><label>Genre<input value={plan.genre} readOnly/></label><label>BPM<input type="number" value={plan.bpm} readOnly/></label><label>Key<select defaultValue="F♯"><option>F♯</option><option>D</option><option>A</option></select></label><label>Duration<select><option>12 seconds</option><option disabled>Long-form (real provider)</option></select></label></div>}<button className="blueprint-toggle" onClick={()=>setBlueprint(v=>!v)}><span><Icon name="spark"/> Song Blueprint</span><Icon name="chevron"/></button>{blueprint&&<div className="blueprint"><div><small>STYLE</small><strong>{plan.genre}</strong></div><div><small>TEMPO</small><strong>{plan.bpm} BPM</strong></div><div><small>TONALITY</small><strong>{plan.key}</strong></div><div><small>FEEL</small><strong>{plan.mood}</strong></div><p><i/>Sparse Rhodes and restrained pocket drums leave room for the final chorus to open up.</p></div>}<button className="generate" onClick={generate} disabled={!prompt.trim()||submitting}><Icon name="spark"/> {submitting?"Starting…":"Generate"}<kbd>⌘ ↵</kbd></button>{notice?<p className="form-notice" role="alert">{notice}</p>:<p className="fineprint">Creates a server-side WAV master · Mock provider</p>}</section>
 <section className="results"><div className="results-head"><div><h2>Generations</h2><span>{songs.length} songs</span></div><button onClick={loadSongs}>Refresh</button></div><div className="result-list">{songs.length===0?<div className="empty"><Icon name="spark"/><h3>Your next sound starts here</h3><p>Describe a song and generate your first durable version.</p></div>:songs.map((s,i)=><SongCard key={s.id} song={s} tone={i%3} active={active} playing={playing} time={time} onPlay={play} onSeek={p=>{setActive(s);setTime(p*s.duration);if(audio.current)audio.current.currentTime=p*s.duration}}/>)}</div></section></div>
 :<section className="library-view"><div className="library-tools"><div className="search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search songs and prompts"/></div><select aria-label="Sort library"><option>Newest first</option><option>Oldest first</option></select></div>{filtered.length?<div className="library-grid">{filtered.map((s,i)=><article key={s.id}><div className="library-cover" data-tone={i%3}><button disabled={!s.audioUrl} onClick={()=>play(s)} aria-label={`Play ${s.title}`}><Icon name={active?.id===s.id&&playing?"pause":"play"}/></button><span>DZ</span></div><h3>{s.title}</h3><p>{s.genre} · V{s.version}</p><small>{new Date(s.createdAt).toLocaleString()}</small></article>)}</div>:<div className="empty"><h3>No songs found</h3><p>Try another search or create your first song.</p></div>}</section>}</main>
 <footer className={`player ${active?"visible":""}`}>{/* Music is instrumental/generated; captions are not applicable. */}<audio ref={audio} src={active?.audioUrl} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/><div className="now"><div className="mini-cover">DZ</div><div><strong>{active?.title||"Choose a song"}</strong><span>{active?`${active.genre} · Version ${active.version}`:"Nothing playing"}</span></div></div><div className="transport"><div><button aria-label="Previous"><Icon name="skip"/></button><button className="main-play" aria-label={playing?"Pause":"Play"} onClick={()=>active&&setPlaying(v=>!v)}><Icon name={playing?"pause":"play"}/></button><button aria-label="Next"><Icon name="skip"/></button></div>{active&&<div className="timeline"><span>{fmt(time)}</span><Wave compact data={active.waveform} progress={time/active.duration} onSeek={p=>{setTime(p*active.duration);if(audio.current)audio.current.currentTime=p*active.duration}}/><span>{fmt(active.duration)}</span></div>}</div><div className="volume"><Icon name="volume"/><input aria-label="Volume" type="range" min="0" max="1" step=".05" defaultValue=".8" onChange={e=>{if(audio.current)audio.current.volume=Number(e.target.value)}}/></div></footer></div>
}

function SongCard({song:s,tone,active,playing,time,onPlay,onSeek}:{song:Song;tone:number;active:Song|null;playing:boolean;time:number;onPlay:(s:Song)=>void;onSeek:(p:number)=>void}){const fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,"0")}`;return <article className="song-card"><div className="cover" data-tone={tone}><span>{s.status==="COMPLETE"?"DZ":s.progress+"%"}</span></div><div className="song-body"><div className="song-title"><div><h3>{s.title}</h3><p>{s.genre} · {s.bpm} BPM · {s.musicalKey}</p></div><div className="song-actions"><button aria-label="Favorite"><Icon name="heart"/></button>{s.audioUrl&&<a href={s.audioUrl} download={`${s.title}.wav`} aria-label="Download WAV"><Icon name="download"/></a>}<button aria-label="More"><Icon name="more"/></button></div></div>{s.status==="COMPLETE"?<Wave data={s.waveform} progress={active?.id===s.id?time/s.duration:0} onSeek={onSeek}/>:<div className="job-progress"><div><i style={{width:`${s.progress}%`}}/></div><span>{labels[s.status]}</span></div>}<div className="song-foot"><button className="play" disabled={s.status!=="COMPLETE"||!s.audioUrl} onClick={()=>onPlay(s)}><Icon name={active?.id===s.id&&playing?"pause":"play"}/></button><span>V{s.version}</span><span>{fmt(s.duration)}</span><span>Seed {s.seed}</span><button className="remix" disabled>Remix</button></div></div></article>}
