"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Status="QUEUED"|"PREPARING"|"GENERATING"|"POST_PROCESSING"|"UPLOADING"|"COMPLETE";
type Song={id:string;title:string;prompt:string;createdAt:string;version:number;duration:number;bpm:number;musicalKey:string;genre:string;status:Status;progress:number;waveform:number[];seed:number};
const peaks=Array.from({length:76},(_,i)=>.14+Math.abs(Math.sin(i*.73)*.7)*(.78+Math.sin(i*.19)*.18));
const demos:Song[]=[{id:"demo-1",title:"After the Long Way Home",prompt:"Warm neo-soul song about finding purpose later in life",createdAt:"Today, 2:14 PM",version:2,duration:32,bpm:76,musicalKey:"F♯ minor",genre:"Neo-soul",status:"COMPLETE",progress:100,waveform:peaks,seed:48127},{id:"demo-2",title:"Amber Static",prompt:"Late-night analog soul with patient drums and electric piano",createdAt:"Yesterday",version:1,duration:28,bpm:82,musicalKey:"D minor",genre:"Alt R&B",status:"COMPLETE",progress:100,waveform:[...peaks].reverse(),seed:19304}];
const path:Record<string,string>={create:"M12 3v18M3 12h18",library:"M4 5v14M9 5v14M14 7v12M19 4v15",play:"m9 7 8 5-8 5V7Z",pause:"M9 7v10M15 7v10",heart:"M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l8.9 8.6 8.8-8.6a5.5 5.5 0 0 0 1.1-8.9Z",more:"M5 12h.01M12 12h.01M19 12h.01",spark:"m12 3-1.4 4.2L7 9l3.6 1.8L12 15l1.4-4.2L17 9l-3.6-1.8L12 3Z",search:"m21 21-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z",skip:"m6 6 8 6-8 6V6Zm10 0v12",volume:"M11 5 6 9H2v6h4l5 4V5Zm4.5 3.5a5 5 0 0 1 0 7",chevron:"m9 18 6-6-6-6",download:"M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"};
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={path[name]}/></svg>}
function Wave({data,progress=0,compact=false,onSeek}:{data:number[];progress?:number;compact?:boolean;onSeek?:(n:number)=>void}){return <button className={`waveform ${compact?"compact":""}`} aria-label="Seek in song" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek?.((e.clientX-r.left)/r.width)}}>{data.map((p,i)=><i key={i} className={i/data.length<=progress?"played":""} style={{height:`${Math.max(10,p*100).toFixed(2)}%`}}/>)}</button>}

export default function StudioApp(){
 const[view,setView]=useState<"create"|"library">("create"),[mode,setMode]=useState<"Simple"|"Advanced">("Simple"),[prompt,setPrompt]=useState("Warm neo-soul song about finding purpose later in life"),[instrumental,setInstrumental]=useState(false),[lyrics,setLyrics]=useState(""),[songs,setSongs]=useState(demos),[active,setActive]=useState<Song|null>(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[search,setSearch]=useState(""),[blueprint,setBlueprint]=useState(true);const audio=useRef<AudioContext|null>(null),osc=useRef<OscillatorNode|null>(null);
 const plan=useMemo(()=>({genre:prompt.toLowerCase().includes("soul")?"Neo-soul":"Alternative pop",bpm:prompt.toLowerCase().includes("slow")?68:76,key:"F♯ minor",mood:prompt.toLowerCase().includes("warm")?"Warm · Reflective":"Intimate · Hopeful"}),[prompt]);
 useEffect(()=>{if(!playing||!active)return;audio.current??=new AudioContext();if(!osc.current){const o=audio.current.createOscillator(),g=audio.current.createGain();o.frequency.value=active.musicalKey.startsWith("F")?185:146;o.type="sine";g.gain.value=.035;o.connect(g).connect(audio.current.destination);o.start();osc.current=o}const t=setInterval(()=>setTime(x=>x>=active.duration?(setPlaying(false),0):x+.1),100);return()=>clearInterval(t)},[playing,active]);useEffect(()=>{if(!playing&&osc.current){osc.current.stop();osc.current=null}},[playing]);
 const play=(s:Song)=>{if(active?.id===s.id)setPlaying(v=>!v);else{setActive(s);setTime(0);setPlaying(true)}};const fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,"0")}`;
 const generate=()=>{if(!prompt.trim())return;const id=crypto.randomUUID(),song:Song={id,title:prompt.toLowerCase().includes("purpose")?"Purpose Finds Us Late":prompt.split(" ").slice(0,4).map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" "),prompt,createdAt:"Just now",version:1,duration:30,bpm:plan.bpm,musicalKey:plan.key,genre:plan.genre,status:"QUEUED",progress:4,waveform:peaks.map((p,i)=>p*(.8+(i%7)/30)),seed:Math.floor(Math.random()*90000)+10000};setSongs(x=>[song,...x]);([["PREPARING",18,600],["GENERATING",52,1500],["POST_PROCESSING",78,2700],["UPLOADING",92,3400],["COMPLETE",100,4100]] as [Status,number,number][]).forEach(([status,progress,delay])=>setTimeout(()=>setSongs(x=>x.map(s=>s.id===id?{...s,status,progress}:s)),delay))};
 const labels:Record<Status,string>={QUEUED:"Queued",PREPARING:"Preparing composition",GENERATING:"Generating audio",POST_PROCESSING:"Analyzing mix",UPLOADING:"Saving master",COMPLETE:"Ready"},filtered=songs.filter(s=>(s.title+s.prompt).toLowerCase().includes(search.toLowerCase()));
 return <div className="app-shell"><aside className="rail"><div className="brand"><span>dz</span></div><nav aria-label="Main navigation"><button className={view==="create"?"active":""} onClick={()=>setView("create")}><Icon name="create"/><span>Create</span></button><button className={view==="library"?"active":""} onClick={()=>setView("library")}><Icon name="library"/><span>Library</span></button></nav><div className="rail-bottom"><button className="avatar" aria-label="Account">FD</button></div></aside><main><header className="topbar"><div><p>DOZI MUSIC STUDIO</p><h1>{view==="create"?"Create":"Your library"}</h1></div><div className="provider"><i/>Mock engine <span>Ready</span></div></header>
 {view==="create"?<div className="workspace"><section className="composer"><div className="mode-tabs">{(["Simple","Advanced"] as const).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m)}>{m}</button>)}</div><label className="field-label" htmlFor="idea">SONG IDEA <span>{prompt.length}/500</span></label><textarea id="idea" value={prompt} maxLength={500} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the song you want to make…"/><div className="toggle-row"><div><strong>Instrumental</strong><small>Create without vocals</small></div><button role="switch" aria-checked={instrumental} className={`switch ${instrumental?"on":""}`} onClick={()=>setInstrumental(v=>!v)}><i/></button></div>{!instrumental&&<><div className="section-head"><span>LYRICS</span><button onClick={()=>setLyrics("[Verse 1]\nThe road got quiet, but I kept the light\n\n[Chorus]\nPurpose finds us in its own sweet time")}>Generate for me <Icon name="spark"/></button></div><textarea className="lyrics" value={lyrics} onChange={e=>setLyrics(e.target.value)} placeholder="Leave blank and Dozi will write lyrics, or add your own…"/></>}{mode==="Advanced"&&<div className="advanced-grid"><label>Genre<input defaultValue={plan.genre}/></label><label>BPM<input type="number" defaultValue={plan.bpm}/></label><label>Key<select defaultValue="F♯"><option>F♯</option><option>D</option><option>A</option></select></label><label>Duration<select><option>30 seconds</option><option>60 seconds</option></select></label></div>}<button className="blueprint-toggle" onClick={()=>setBlueprint(v=>!v)}><span><Icon name="spark"/> Song Blueprint</span><Icon name="chevron"/></button>{blueprint&&<div className="blueprint"><div><small>STYLE</small><strong>{plan.genre}</strong></div><div><small>TEMPO</small><strong>{plan.bpm} BPM</strong></div><div><small>TONALITY</small><strong>{plan.key}</strong></div><div><small>FEEL</small><strong>{plan.mood}</strong></div><p><i/>Sparse Rhodes and restrained pocket drums leave room for the final chorus to open up.</p></div>}<button className="generate" onClick={generate} disabled={!prompt.trim()}><Icon name="spark"/> Generate <kbd>⌘ ↵</kbd></button><p className="fineprint">Creates 1 version · Deterministic mock engine</p></section>
 <section className="results"><div className="results-head"><div><h2>Generations</h2><span>{songs.length} songs</span></div><button onClick={()=>setSongs([])}>Clear</button></div><div className="result-list">{songs.length===0?<div className="empty"><Icon name="spark"/><h3>Your next sound starts here</h3><p>Describe a song and generate your first version.</p></div>:songs.map((s,i)=><article className="song-card" key={s.id}><div className="cover" data-tone={i%3}><span>{s.status==="COMPLETE"?"DZ":s.progress+"%"}</span></div><div className="song-body"><div className="song-title"><div><h3>{s.title}</h3><p>{s.genre} · {s.bpm} BPM · {s.musicalKey}</p></div><div className="song-actions"><button aria-label="Favorite"><Icon name="heart"/></button><button aria-label="Download"><Icon name="download"/></button><button aria-label="More"><Icon name="more"/></button></div></div>{s.status==="COMPLETE"?<Wave data={s.waveform} progress={active?.id===s.id?time/s.duration:0} onSeek={p=>{setActive(s);setTime(p*s.duration)}}/>:<div className="job-progress"><div><i style={{width:`${s.progress}%`}}/></div><span>{labels[s.status]}</span></div>}<div className="song-foot"><button className="play" disabled={s.status!=="COMPLETE"} onClick={()=>play(s)}><Icon name={active?.id===s.id&&playing?"pause":"play"}/></button><span>V{s.version}</span><span>{fmt(s.duration)}</span><span>Seed {s.seed}</span><button className="remix" disabled={s.status!=="COMPLETE"}>Remix</button></div></div></article>)}</div></section></div>
 :<section className="library-view"><div className="library-tools"><div className="search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search songs and prompts"/></div><select aria-label="Sort library"><option>Newest first</option><option>Oldest first</option></select></div><div className="library-grid">{filtered.map((s,i)=><article key={s.id}><div className="library-cover" data-tone={i%3}><button onClick={()=>play(s)} aria-label={`Play ${s.title}`}><Icon name={active?.id===s.id&&playing?"pause":"play"}/></button><span>DZ</span></div><h3>{s.title}</h3><p>{s.genre} · V{s.version}</p><small>{s.createdAt}</small></article>)}</div></section>}</main>
 <footer className={`player ${active?"visible":""}`}><div className="now"><div className="mini-cover">DZ</div><div><strong>{active?.title||"Choose a song"}</strong><span>{active?`${active.genre} · Version ${active.version}`:"Nothing playing"}</span></div></div><div className="transport"><div><button aria-label="Previous"><Icon name="skip"/></button><button className="main-play" aria-label={playing?"Pause":"Play"} onClick={()=>active&&setPlaying(v=>!v)}><Icon name={playing?"pause":"play"}/></button><button aria-label="Next"><Icon name="skip"/></button></div>{active&&<div className="timeline"><span>{fmt(time)}</span><Wave compact data={active.waveform} progress={time/active.duration} onSeek={p=>setTime(p*active.duration)}/><span>{fmt(active.duration)}</span></div>}</div><div className="volume"><Icon name="volume"/><input aria-label="Volume" type="range" min="0" max="1" step=".05" defaultValue=".8"/></div></footer></div>
}
