export const GENERATION_STATES=["QUEUED","PREPARING","GENERATING","POST_PROCESSING","UPLOADING","COMPLETE","FAILED","CANCELLED"] as const;
export type GenerationStatus=(typeof GENERATION_STATES)[number];
export type CompositionPlan={titleSuggestions:string[];genre:string;subgenres:string[];mood:string[];bpm:number;key:string;scale:string;timeSignature:string;durationSeconds:number;instrumentation:{instrument:string;role:string;character:string}[];vocal:{enabled:boolean;tone:string;delivery:string};structure:{type:string;bars:number;energy:number;description:string}[];generationCaption:string;negativeInstructions:string[]};
export type CreateGeneration={prompt:string;lyrics?:string;instrumental?:boolean;genre?:string;bpm?:number;key?:string;durationSeconds?:number;seed?:number};

export function validateGeneration(input:unknown):CreateGeneration{
 if(!input||typeof input!=="object")throw new Error("INVALID_REQUEST");const v=input as Record<string,unknown>;const prompt=typeof v.prompt==="string"?v.prompt.trim():"";if(prompt.length<8||prompt.length>500)throw new Error("INVALID_PROMPT");
 const duration=typeof v.durationSeconds==="number"?v.durationSeconds:12;if(duration<5||duration>60)throw new Error("INVALID_DURATION");
 return{prompt,lyrics:typeof v.lyrics==="string"?v.lyrics.slice(0,10000):"",instrumental:v.instrumental===true,genre:typeof v.genre==="string"?v.genre.slice(0,80):undefined,bpm:typeof v.bpm==="number"?Math.max(40,Math.min(220,Math.round(v.bpm))):undefined,key:typeof v.key==="string"?v.key.slice(0,20):undefined,durationSeconds:duration,seed:typeof v.seed==="number"?Math.abs(Math.round(v.seed)):undefined};
}

export function compose(request:CreateGeneration):CompositionPlan{
 const p=request.prompt.toLowerCase(),genre=request.genre||(p.includes("soul")?"Neo-soul":p.includes("jazz")?"Contemporary jazz":p.includes("rock")?"Alternative rock":"Alternative pop"),bpm=request.bpm||(p.includes("slow")||p.includes("reflective")?72:p.includes("dance")?118:84),key=request.key||(p.includes("bright")?"A":"F#"),mood=[p.includes("warm")?"Warm":"Intimate",p.includes("purpose")?"Hopeful":"Reflective"];
 return{titleSuggestions:[p.includes("purpose")?"Purpose Finds Us Late":request.prompt.split(/\s+/).slice(0,4).map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ")],genre,subgenres:p.includes("soul")?["alternative R&B"]:[],mood,bpm,key,scale:p.includes("bright")?"major":"minor",timeSignature:"4/4",durationSeconds:request.durationSeconds||12,instrumentation:[{instrument:"Rhodes",role:"harmonic bed",character:"warm and restrained"},{instrument:"Pocket drums",role:"groove",character:"human and spacious"},{instrument:"Electric bass",role:"low-end movement",character:"round and melodic"}],vocal:{enabled:!request.instrumental,tone:"intimate and textured",delivery:"conversational verses, open chorus"},structure:[{type:"intro",bars:4,energy:.2,description:"Sparse harmonic motif"},{type:"verse",bars:8,energy:.45,description:"Patient narrative development"},{type:"chorus",bars:8,energy:.78,description:"Wider harmony and stronger drums"},{type:"outro",bars:4,energy:.3,description:"Resolve to the opening motif"}],generationCaption:`${genre}, ${bpm} BPM, ${key} ${p.includes("bright")?"major":"minor"}, ${mood.join(" and ")}; warm Rhodes, pocket drums, melodic bass`,negativeInstructions:["harsh limiting","abrupt ending","undifferentiated loop"]};
}
