import type { GeneratedAsset, GenerationRequest, GenerationResult, ProviderCapabilities, ProviderHealth } from "./domain";
import type { MusicGenerationProvider as Provider } from "./provider-types";
import { createDeterministicWav } from "./wav";
export type { GeneratedAsset, GenerationRequest, GenerationResult, ProviderCapabilities, ProviderHealth } from "./domain";
export type MusicGenerationProvider=Provider;

const capabilities=(multi=false):ProviderCapabilities=>({textToMusic:true,lyrics:true,referenceAudio:false,continuation:false,repaint:false,stems:false,nativeMultitrack:multi,bpmControl:true,keyControl:true,seed:true});
const definitions=[{role:"MASTER",instrument:undefined,group:undefined},{role:"PREMASTER",instrument:undefined,group:undefined},{role:"NATIVE_TRACK",instrument:"Kick",group:"DRUMS"},{role:"NATIVE_TRACK",instrument:"Snare",group:"DRUMS"},{role:"NATIVE_TRACK",instrument:"Bass",group:"MUSIC"},{role:"NATIVE_TRACK",instrument:"Lead Vocal",group:"VOCALS"}] as const;
export class MockMusicProvider implements MusicGenerationProvider{readonly name="mock";readonly model="dozi-deterministic-multiasset-v2";capabilities(){return capabilities(true)}async healthCheck():Promise<ProviderHealth>{return{available:true,latencyMs:0,message:"Deterministic multi-asset provider ready"}}async generate(request:GenerationRequest):Promise<GenerationResult>{const wanted=request.outputMode==="MULTI_ASSET"?definitions:definitions.slice(0,1),assets:GeneratedAsset[]=[];for(const [sortOrder,item] of wanted.entries()){const wav=await createDeterministicWav(request.seed+sortOrder*97,request.compositionPlan.durationSeconds,request.compositionPlan.bpm);assets.push({assetKey:`${item.role.toLowerCase()}-${item.instrument?.toLowerCase().replaceAll(" ","-")||"mix"}`,role:item.role,instrument:item.instrument,instrumentGroup:item.group,provenance:"GENERATED_NATIVE",isPrimary:item.role==="MASTER",sortOrder,audio:{bytes:new Uint8Array(wav.buffer)},metadata:{mimeType:"audio/wav",codec:"pcm_s16le",sampleRate:wav.sampleRate,bitDepth:wav.bitDepth,channels:wav.channels,durationSeconds:request.compositionPlan.durationSeconds,checksum:wav.checksum,waveformData:wav.waveform}})}return{assets,providerMetadata:{mode:request.outputMode}}}}
export class AceStepMusicProvider implements MusicGenerationProvider{readonly name="acestep";readonly model="unconfigured";capabilities():ProviderCapabilities{return{...capabilities(false),textToMusic:false,lyrics:false,bpmControl:false,keyControl:false,seed:false}}async healthCheck():Promise<ProviderHealth>{return{available:false,latencyMs:0,message:"ACE-Step is intentionally not integrated in this phase"}}async generate():Promise<never>{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}}
export class AiServiceMusicProvider implements MusicGenerationProvider{readonly name="ai-service";readonly model="fastapi-mock-v1";constructor(private readonly baseUrl:string,private readonly token?:string){}capabilities(){return capabilities(true)}async healthCheck():Promise<ProviderHealth>{const started=Date.now();try{const response=await fetch(`${this.baseUrl}/health`,{headers:this.headers()});return{available:response.ok,latencyMs:Date.now()-started,message:response.ok?"AI service ready":"AI service unhealthy"}}catch{return{available:false,latencyMs:Date.now()-started,message:"AI service unavailable"}}}async generate(request:GenerationRequest):Promise<GenerationResult>{const response=await fetch(`${this.baseUrl}/v1/mock-generation`,{method:"POST",headers:{...this.headers(),"content-type":"application/json"},body:JSON.stringify({...request,audioTransport:"INLINE_TEST"})});if(!response.ok)throw new Error("AI_SERVICE_GENERATION_FAILED");const json=await response.json() as {assets:Array<Omit<GeneratedAsset,"audio">&{audio:{base64:string}}> ;providerMetadata?:Record<string,unknown>};return{providerMetadata:json.providerMetadata,assets:json.assets.map(asset=>({...asset,audio:{bytes:Uint8Array.from(atob(asset.audio.base64),c=>c.charCodeAt(0))}}))}}private headers():Record<string,string>{return this.token?{authorization:`Bearer ${this.token}`}:{}}}
export function createProvider(name:string,config:{aiServiceBaseUrl?:string;aiServiceToken?:string}={}):MusicGenerationProvider{if(name==="mock")return new MockMusicProvider();if(name==="ai-service"&&config.aiServiceBaseUrl)return new AiServiceMusicProvider(config.aiServiceBaseUrl,config.aiServiceToken);if(name==="acestep")return new AceStepMusicProvider();throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
export const providers={mock:new MockMusicProvider(),acestep:new AceStepMusicProvider()};
