import { kieInput } from "./kie-input";
import { contextualTrackGenerationSchema } from "./domain";
import type { ContextualTrackGenerationRequest, CoverReference, GeneratedAsset, GenerationRequest, GenerationResult, ProviderCapabilities, ProviderHealth } from "./domain";
import type { MusicGenerationProvider as Provider } from "./provider-types";
import { createDeterministicWav } from "./wav";
export type { GeneratedAsset, GenerationRequest, GenerationResult, ProviderCapabilities, ProviderHealth } from "./domain";
export type MusicGenerationProvider=Provider;

const capabilities=(multi=false):ProviderCapabilities=>({textToMusic:true,lyrics:true,referenceAudio:false,continuation:false,repaint:false,stems:false,nativeMultitrack:multi,masterGeneration:"DEVELOPMENT",contextualRegeneration:"UNAVAILABLE",sourceSeparation:"UNAVAILABLE",bpmControl:true,keyControl:true,seed:true});
const definitions=[{role:"MASTER",instrument:undefined,group:undefined},{role:"PREMASTER",instrument:undefined,group:undefined},{role:"NATIVE_TRACK",instrument:"Kick",group:"DRUMS"},{role:"NATIVE_TRACK",instrument:"Snare",group:"DRUMS"},{role:"NATIVE_TRACK",instrument:"Bass",group:"MUSIC"},{role:"NATIVE_TRACK",instrument:"Lead Vocal",group:"VOCALS"}] as const;
export class MockMusicProvider implements MusicGenerationProvider{readonly name="mock";readonly model="dozi-deterministic-multiasset-v2";capabilities(){return capabilities(true)}async healthCheck():Promise<ProviderHealth>{return{available:true,latencyMs:0,message:"Deterministic multi-asset provider ready"}}async generate(request:GenerationRequest):Promise<GenerationResult>{const wanted=request.outputMode==="MULTI_ASSET"?definitions:definitions.slice(0,1),assets:GeneratedAsset[]=[];for(const [sortOrder,item] of wanted.entries()){const wav=await createDeterministicWav(request.seed+sortOrder*97,request.compositionPlan.durationSeconds,request.compositionPlan.bpm);assets.push({assetKey:`${item.role.toLowerCase()}-${item.instrument?.toLowerCase().replaceAll(" ","-")||"mix"}`,role:item.role,instrument:item.instrument,instrumentGroup:item.group,provenance:"GENERATED_NATIVE",isPrimary:item.role==="MASTER",sortOrder,audio:{bytes:new Uint8Array(wav.buffer)},metadata:{mimeType:"audio/wav",codec:"pcm_s16le",sampleRate:wav.sampleRate,bitDepth:wav.bitDepth,channels:wav.channels,durationSeconds:request.compositionPlan.durationSeconds,checksum:wav.checksum,waveformData:wav.waveform}})}return{assets,providerMetadata:{mode:request.outputMode}}}}
class GatewayProvider implements MusicGenerationProvider{constructor(readonly name:string,readonly model:string,private readonly baseUrl:string,private readonly endpoint:string,private readonly token?:string,private readonly readinessKey?:"aceStep"|"minimax"){}capabilities(){return capabilities(false)}async healthCheck():Promise<ProviderHealth>{const started=Date.now();try{const response=await fetch(`${this.baseUrl}/health`,{headers:this.headers()}),body=await response.json() as {aceStep?:{ready?:boolean};minimax?:{ready?:boolean}};const ready=!this.readinessKey||body[this.readinessKey]?.ready===true;return{available:response.ok&&ready,latencyMs:Date.now()-started,message:ready?"AI service and provider ready":`${this.name} model service unavailable`}}catch{return{available:false,latencyMs:Date.now()-started,message:"AI service unavailable"}}}async generate(request:GenerationRequest):Promise<GenerationResult>{let response:Response;try{response=await fetch(`${this.baseUrl}${this.endpoint}`,{method:"POST",headers:{...this.headers(),"content-type":"application/json"},body:JSON.stringify(request)})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:{code?:string}}|null;throw new Error(body?.detail?.code||"GENERATION_PROVIDER_FAILED")}const json=await response.json() as {assets:Array<Omit<GeneratedAsset,"audio">&{audio:{base64?:string;sourceUrl?:string}}> ;providerMetadata?:Record<string,unknown>};const assets:GeneratedAsset[]=[];for(const asset of json.assets){let bytes:Uint8Array;if(asset.audio.sourceUrl){const audioResponse=await fetch(asset.audio.sourceUrl,{headers:this.headers()});if(!audioResponse.ok)throw new Error("GENERATION_INVALID_RESULT");bytes=new Uint8Array(await audioResponse.arrayBuffer())}else if(asset.audio.base64)bytes=Uint8Array.from(atob(asset.audio.base64),c=>c.charCodeAt(0));else throw new Error("GENERATION_INVALID_RESULT");assets.push({...asset,audio:{bytes}})}return{providerMetadata:json.providerMetadata,assets}}private headers():Record<string,string>{return this.token?{authorization:`Bearer ${this.token}`}:{}}}
export class AiServiceMusicProvider extends GatewayProvider{constructor(baseUrl:string,token?:string){super("ai-service","fastapi-mock-v1",baseUrl,"/v1/mock-generation",token)}}
export class AceStepMusicProvider extends GatewayProvider{
  constructor(private readonly gatewayUrl="",private readonly gatewayToken?:string,model="acestep-v15-xl-base"){super("acestep",model,gatewayUrl,"/v1/ace-step-generation",gatewayToken,"aceStep")}
  override capabilities(){return{...super.capabilities(),nativeMultitrack:false,referenceAudio:true,masterGeneration:"EXPERIMENTAL" as const,contextualRegeneration:"EXPERIMENTAL" as const}}
  async generateCover(request:GenerationRequest,reference:CoverReference):Promise<GenerationResult>{
    let response:Response;
    try{response=await fetch(`${this.gatewayUrl}/v1/ace-step-cover`,{method:"POST",headers:{...(this.gatewayToken?{authorization:`Bearer ${this.gatewayToken}`}:{}) ,"content-type":"application/json"},body:JSON.stringify({...request,sourceAssetId:reference.sourceAssetId,sourceTitle:reference.sourceTitle,sourceMimeType:reference.sourceMimeType,sourceAudioBase64:bytesToBase64(reference.sourceAudio),arrangement:reference.arrangement,sourceAdherence:reference.sourceAdherence,styleInfluence:reference.styleInfluence})})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:{code?:string}}|null;throw new Error(body?.detail?.code||"GENERATION_PROVIDER_FAILED")}
    return readGatewayResult(await response.json() as GatewayResult,this.gatewayToken);
  }
  async generateContextualTrack(request:ContextualTrackGenerationRequest){contextualTrackGenerationSchema.parse(request);let response:Response;try{response=await fetch(`${this.gatewayUrl}/v1/ace-step-lego`,{method:"POST",headers:{...(this.gatewayToken?{authorization:`Bearer ${this.gatewayToken}`}:{}) ,"content-type":"application/json"},body:JSON.stringify({...request,sourceAudioBase64:bytesToBase64(request.sourceAudio),sourceAudio:undefined})})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:{code?:string}}|null;throw new Error(body?.detail?.code||"GENERATION_PROVIDER_FAILED")}return readGatewayResult(await response.json() as GatewayResult,this.gatewayToken)}
}
export class MiniMaxMusicProvider extends GatewayProvider{constructor(baseUrl:string,token?:string,model="MiniMax-Music3-mxfp8"){super("minimax",model,baseUrl,"/v1/minimax-generation",token,"minimax")}override capabilities(){return{...super.capabilities(),masterGeneration:"EXPERIMENTAL" as const,nativeMultitrack:false}}}
export class ElevenLabsMusicProvider implements MusicGenerationProvider{
  readonly name="elevenlabs";
  constructor(private readonly apiKey:string,readonly model="music_v2",private readonly baseUrl="https://api.elevenlabs.io"){}
  capabilities():ProviderCapabilities{return{...capabilities(false),masterGeneration:"EXPERIMENTAL",seed:false}}
  async healthCheck():Promise<ProviderHealth>{return{available:Boolean(this.apiKey),latencyMs:0,message:this.apiKey?"Eleven Music configured (generation not yet charged)":"ElevenLabs API key missing"}}
  async generate(request:GenerationRequest):Promise<GenerationResult>{
    if(request.outputMode!=="MASTER_ONLY")throw new Error("PROVIDER_OUTPUT_MODE_UNSUPPORTED");
    let response:Response;
    try{response=await fetch(`${this.baseUrl}/v1/music?output_format=mp3_48000_192`,{method:"POST",headers:{"xi-api-key":this.apiKey,"content-type":"application/json","accept":"audio/mpeg"},body:JSON.stringify({prompt:elevenLabsPrompt(request),music_length_ms:Math.max(3000,request.compositionPlan.durationSeconds*1000),model_id:this.model,force_instrumental:request.compositionPlan.vocal.enabled===false})})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:{status?:string}}|null,status=body?.detail?.status;if(status==="bad_prompt"||status==="bad_composition_plan")throw new Error("PROVIDER_PROMPT_REJECTED");throw new Error(elevenLabsError(response.status,response.headers.get("request-id")||undefined))}
    const bytes=new Uint8Array(await response.arrayBuffer());
    if(bytes.length===0)throw new Error("GENERATION_INVALID_RESULT");
    return{assets:[{assetKey:"master-mix",role:"MASTER",provenance:"GENERATED_NATIVE",isPrimary:true,sortOrder:0,audio:{bytes},metadata:{mimeType:response.headers.get("content-type")?.split(";")[0]||"audio/mpeg",codec:"mp3",sampleRate:48000,bitDepth:16,channels:2,durationSeconds:Math.max(3,request.compositionPlan.durationSeconds),waveformData:[]},providerMetadata:{generationMethod:"FULL_SONG",songId:response.headers.get("song-id")||undefined,model:this.model}}],providerMetadata:{model:this.model}}
  }
  async generateCover(request:GenerationRequest,reference:CoverReference):Promise<GenerationResult>{
    if(!["music_v2","music_v2_5"].includes(this.model))throw new Error("COVER_PROVIDER_UNSUPPORTED");
    const upload=new FormData(),extension=reference.sourceMimeType.includes("mpeg")?"mp3":reference.sourceMimeType.includes("mp4")?"m4a":"wav",referenceBytes=new Uint8Array(reference.sourceAudio);
    upload.set("file",new Blob([referenceBytes.buffer as ArrayBuffer],{type:reference.sourceMimeType}),`private-reference.${extension}`);
    upload.set("extract_composition_plan",this.model);
    let uploaded:Response;
    try{uploaded=await fetch(`${this.baseUrl}/v1/music/upload`,{method:"POST",headers:{"xi-api-key":this.apiKey},body:upload})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    const uploadBody=await uploaded.json().catch(()=>null) as {song_id?:string;detail?:{status?:string}}|null;
    if(!uploaded.ok||!uploadBody?.song_id)throw new Error(coverUploadError(uploaded.status,uploadBody?.detail?.status));
    const durationMs=Math.max(3000,request.compositionPlan.durationSeconds*1000),referenceEndMs=Math.max(3000,Math.min(30000,Math.floor(reference.sourceDurationSeconds*1000))),text=request.lyrics?.trim()||"[Cover performance]",styles=[request.compositionPlan.genre,`${request.compositionPlan.bpm} BPM`,`${request.compositionPlan.key} ${request.compositionPlan.scale}`,request.compositionPlan.generationCaption,"polished full-band production"].filter(Boolean).map(value=>String(value).slice(0,180)),strength=reference.arrangement==="FAITHFUL"?"xhigh":reference.arrangement==="REFRESH"?"high":"medium",adherence=reference.arrangement==="NEW"?"medium":"high";
    let response:Response;
    try{response=await fetch(`${this.baseUrl}/v1/music?output_format=mp3_48000_192`,{method:"POST",headers:{"xi-api-key":this.apiKey,"content-type":"application/json","accept":"audio/mpeg"},body:JSON.stringify({composition_plan:{chunks:[{text,duration_ms:durationMs,positive_styles:styles,negative_styles:request.compositionPlan.negativeInstructions,context_adherence:adherence,conditioning_ref:{song_id:uploadBody.song_id,range:{start_ms:0,end_ms:referenceEndMs}},condition_strength:strength}]},model_id:this.model})})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:{status?:string}}|null;throw new Error(elevenLabsError(response.status,body?.detail?.status))}
    const bytes=new Uint8Array(await response.arrayBuffer());
    if(!bytes.length)throw new Error("GENERATION_INVALID_RESULT");
    const metadata={generationMethod:"COVER_REIMAGINE",sourceTitle:reference.sourceTitle,sourceAssetId:reference.sourceAssetId,referenceSongId:uploadBody.song_id,referenceSeconds:referenceEndMs/1000,arrangement:reference.arrangement,model:this.model};
    return{assets:[{assetKey:"cover-master",role:"MASTER",provenance:"GENERATED_NATIVE",isPrimary:true,sortOrder:0,sourceAssetId:reference.sourceAssetId,audio:{bytes},metadata:{mimeType:response.headers.get("content-type")?.split(";")[0]||"audio/mpeg",codec:"mp3",sampleRate:48000,bitDepth:16,channels:2,durationSeconds:durationMs/1000,waveformData:[]},providerMetadata:metadata}],providerMetadata:metadata};
  }
}
export class KieMusicProvider implements MusicGenerationProvider{
  readonly name="kie";
  constructor(private readonly apiKey:string,readonly model="V6",private readonly baseUrl="https://api.kie.ai",private readonly uploadBaseUrl="https://kieai.redpandaai.co",private readonly pollIntervalMs=5000){}
  capabilities():ProviderCapabilities{return{...capabilities(false),referenceAudio:true,masterGeneration:"EXPERIMENTAL",seed:false}}
  async healthCheck():Promise<ProviderHealth>{return{available:Boolean(this.apiKey),latencyMs:0,message:this.apiKey?"Kie.ai configured (generation not yet charged)":"Kie.ai API key missing"}}
  async generate(request:GenerationRequest):Promise<GenerationResult>{
    if(request.outputMode!=="MASTER_ONLY")throw new Error("PROVIDER_OUTPUT_MODE_UNSUPPORTED");
    return this.createAndWait("ai-music-api/generate",this.input(request),request);
  }
  async generateCover(request:GenerationRequest,reference:CoverReference):Promise<GenerationResult>{
    if(request.outputMode!=="MASTER_ONLY")throw new Error("PROVIDER_OUTPUT_MODE_UNSUPPORTED");
    if(reference.sourceDurationSeconds>480)throw new Error("COVER_REFERENCE_TOO_LONG");
    const uploadUrl=await this.upload(reference);
    return this.createAndWait("ai-music-api/upload-and-cover-audio",{...kieInput(request,this.model,true),upload_url:uploadUrl},request,reference);
  }
  private input(request:GenerationRequest){return kieInput(request,this.model)}
  private headers(){return{authorization:`Bearer ${this.apiKey}`}}
  private async upload(reference:CoverReference){
    const extension=reference.sourceMimeType.includes("mpeg")?"mp3":reference.sourceMimeType.includes("mp4")?"m4a":"wav",form=new FormData(),bytes=new Uint8Array(reference.sourceAudio);
    form.set("file",new Blob([bytes.buffer as ArrayBuffer],{type:reference.sourceMimeType}),`private-cover.${extension}`);form.set("uploadPath","dozi/covers");form.set("fileName",`private-cover.${extension}`);
    let response:Response;try{response=await fetch(`${this.uploadBaseUrl}/api/file-stream-upload`,{method:"POST",headers:this.headers(),body:form})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    const body=await response.json().catch(()=>null) as {data?:{downloadUrl?:string};message?:string}|null;
    if(!response.ok||!body?.data?.downloadUrl)throw new Error(kieError(response.status,"COVER_REFERENCE_UPLOAD_FAILED"));
    return body.data.downloadUrl;
  }
  private async createAndWait(operation:string,input:Record<string,unknown>,request:GenerationRequest,reference?:CoverReference):Promise<GenerationResult>{
    let response:Response;try{response=await fetch(`${this.baseUrl}/api/v1/jobs/createTask`,{method:"POST",headers:{...this.headers(),"content-type":"application/json"},body:JSON.stringify({model:operation,input})})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
    const created=await response.json().catch(()=>null) as {data?:{taskId?:string;task_id?:string};message?:string}|null,taskId=created?.data?.taskId||created?.data?.task_id;
    if(!response.ok||!taskId)throw new Error(kieError(response.status));
    const track=await this.waitForTrack(taskId),audio=await this.download(track.audioUrl),duration=typeof track.duration==="number"&&track.duration>0?track.duration:request.compositionPlan.durationSeconds,metadata={generationMethod:reference?"COVER_REIMAGINE":"FULL_SONG",taskId,trackId:track.id,title:track.title,model:track.model||this.model,sourceAssetId:reference?.sourceAssetId,sourceTitle:reference?.sourceTitle,arrangement:reference?.arrangement};
    return{assets:[{assetKey:reference?"kie-cover-master":"kie-master",role:"MASTER",provenance:"GENERATED_NATIVE",isPrimary:true,sortOrder:0,sourceAssetId:reference?.sourceAssetId,audio:{bytes:audio.bytes},metadata:{mimeType:audio.mimeType,codec:audio.mimeType.includes("mpeg")?"mp3":"audio",sampleRate:44100,bitDepth:16,channels:2,durationSeconds:duration,waveformData:[]},providerMetadata:metadata}],providerMetadata:metadata};
  }
  private async waitForTrack(taskId:string){
    for(let attempt=0;attempt<240;attempt++){
      let response:Response;try{response=await fetch(`${this.baseUrl}/api/v1/jobs/recordInfo?taskId=${encodeURIComponent(taskId)}`,{headers:this.headers()})}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
      const body=await response.json().catch(()=>null) as unknown;if(!response.ok)throw new Error(kieError(response.status));
      const status=kieStatus(body),track=kieTrack(body);if(track)return track;if(status.includes("FAIL")||status.includes("ERROR"))throw new Error("GENERATION_PROVIDER_FAILED");
      if(this.pollIntervalMs>0)await new Promise(resolve=>setTimeout(resolve,this.pollIntervalMs));
    }
    throw new Error("GENERATION_TIMEOUT");
  }
  private async download(url:string){let response:Response;try{response=await fetch(url)}catch{throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}if(!response.ok)throw new Error("GENERATION_INVALID_RESULT");const bytes=new Uint8Array(await response.arrayBuffer());if(!bytes.length)throw new Error("GENERATION_INVALID_RESULT");return{bytes,mimeType:response.headers.get("content-type")?.split(";")[0]||"audio/mpeg"}}
}
export type ProviderConfig={aiServiceBaseUrl?:string;aiServiceToken?:string;aceStepModel?:string;minimaxModel?:string;elevenLabsApiKey?:string;elevenLabsModel?:string;kieApiKey?:string;kieModel?:string};
export function createProvider(name:string,config:ProviderConfig={}):MusicGenerationProvider{if(name==="mock")return new MockMusicProvider();if(name==="ai-service"&&config.aiServiceBaseUrl)return new AiServiceMusicProvider(config.aiServiceBaseUrl,config.aiServiceToken);if(name==="acestep"&&config.aiServiceBaseUrl)return new AceStepMusicProvider(config.aiServiceBaseUrl,config.aiServiceToken,config.aceStepModel);if(name==="minimax"&&config.aiServiceBaseUrl)return new MiniMaxMusicProvider(config.aiServiceBaseUrl,config.aiServiceToken,config.minimaxModel);if(name==="elevenlabs"&&config.elevenLabsApiKey)return new ElevenLabsMusicProvider(config.elevenLabsApiKey,config.elevenLabsModel);if(name==="kie"&&config.kieApiKey)return new KieMusicProvider(config.kieApiKey,config.kieModel);throw new Error("GENERATION_PROVIDER_UNAVAILABLE")}
export const providers={mock:new MockMusicProvider()};
function bytesToBase64(bytes:Uint8Array){let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
type GatewayResult={assets:Array<Omit<GeneratedAsset,"audio">&{audio:{base64?:string;sourceUrl?:string}}> ;providerMetadata?:Record<string,unknown>};
async function readGatewayResult(json:GatewayResult,token?:string):Promise<GenerationResult>{const assets:GeneratedAsset[]=[];for(const asset of json.assets){let bytes:Uint8Array;if(asset.audio.sourceUrl){const response=await fetch(asset.audio.sourceUrl,{headers:token?{authorization:`Bearer ${token}`}:{}});if(!response.ok)throw new Error("GENERATION_INVALID_RESULT");bytes=new Uint8Array(await response.arrayBuffer())}else if(asset.audio.base64)bytes=Uint8Array.from(atob(asset.audio.base64),c=>c.charCodeAt(0));else throw new Error("GENERATION_INVALID_RESULT");assets.push({...asset,audio:{bytes}})}return{providerMetadata:json.providerMetadata,assets}}
function elevenLabsPrompt(request:GenerationRequest){const plan=request.compositionPlan,instruments=plan.instrumentation.map(item=>`${item.instrument} (${item.character})`).join(", "),sections=plan.structure.map(item=>`${item.type}: ${item.description}`).join("; "),lyrics=request.lyrics?.trim(),vocalDirection=plan.vocal.enabled?(lyrics?`Use these lyrics:\n${lyrics}`:`Include an original lead vocal performance and write original lyrics that fit the concept. Vocal tone: ${plan.vocal.tone}; delivery: ${plan.vocal.delivery}.`):"Instrumental only; no vocals.";return[`Create an original ${plan.genre} song.`,plan.generationCaption,`${plan.bpm} BPM, ${plan.tonalitySpecified === false ? "choose a fitting key" : `${plan.key} ${plan.scale}`}, ${plan.timeSignature}.`,`Mood: ${plan.mood.join(", ")}.`,`Instrumentation: ${instruments}.`,`Structure: ${sections}.`,`Avoid: ${plan.negativeInstructions.join(", ")}.`,vocalDirection].join(" ").slice(0,4100)}
function elevenLabsError(status:number,requestId?:string){const code=status===401||status===403?"PROVIDER_AUTHORIZATION_FAILED":status===429?"PROVIDER_RATE_LIMITED":status>=500?"GENERATION_PROVIDER_UNAVAILABLE":"GENERATION_PROVIDER_FAILED";return requestId?`${code}:${requestId}`:code}
function coverUploadError(status:number,providerStatus?:string){if(status===401||status===403)return"PROVIDER_AUTHORIZATION_FAILED";if(status===429)return"PROVIDER_RATE_LIMITED";if(status>=500)return"GENERATION_PROVIDER_UNAVAILABLE";if(providerStatus==="copyright_infringement"||providerStatus==="copyright_violation")return"COVER_REFERENCE_REJECTED";return"COVER_REFERENCE_UPLOAD_FAILED"}
function kieError(status:number,fallback="GENERATION_PROVIDER_FAILED"){if(status===401||status===403)return"PROVIDER_AUTHORIZATION_FAILED";if(status===429)return"PROVIDER_RATE_LIMITED";if(status>=500)return"GENERATION_PROVIDER_UNAVAILABLE";return fallback}
function kieRecord(value:unknown):Record<string,unknown>|undefined{return value!==null&&typeof value==="object"?value as Record<string,unknown>:undefined}
function kiePayload(value:unknown){const root=kieRecord(value),data=kieRecord(root?.data);let result:unknown=data?.resultJson??data?.result_json;if(typeof result==="string")try{result=JSON.parse(result)}catch{result=undefined}return{data,result:kieRecord(result)}}
function kieStatus(value:unknown){const {data}=kiePayload(value),status=data?.status??data?.state;return typeof status==="string"?status.toUpperCase():""}
function kieTrack(value:unknown){const {data,result}=kiePayload(value),response=kieRecord(data?.response)??kieRecord(result?.response)??result,candidates=response?.sunoData??response?.suno_data??response?.data??data?.sunoData;if(!Array.isArray(candidates))return undefined;for(const item of candidates){const track=kieRecord(item),audioUrl=track?.audio_url??track?.audioUrl;if(typeof audioUrl!=="string"||!audioUrl)continue;return{id:typeof track?.id==="string"?track.id:"kie-track",title:typeof track?.title==="string"?track.title:"Dozi song",audioUrl,duration:typeof track?.duration==="number"?track.duration:undefined,model:typeof track?.model_name==="string"?track.model_name:undefined}}return undefined}
