import { sql } from "drizzle-orm";
import { boolean, check, doublePrecision, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import type { CompositionPlan } from "../lib/domain";

export const generationStatusEnum=pgEnum("generation_status",["QUEUED","PREPARING","GENERATING","POST_PROCESSING","UPLOADING","COMPLETE","FAILED","CANCELLED"]);
export const assetRoleEnum=pgEnum("audio_asset_role",["MASTER","PREMASTER","NATIVE_TRACK","DERIVED_STEM","EFFECT_RETURN","ALTERNATIVE","REFERENCE","UPLOAD"]);
export const provenanceEnum=pgEnum("generation_provenance",["GENERATED_NATIVE","SEPARATED","RENDERED","UPLOADED","REFERENCE","DERIVED"]);
export const trackGenerationMethodEnum=pgEnum("track_generation_method",["FULL_SONG","LEGO_CONTEXTUAL","EXTRACT","COMPLETE","SEPARATION","UPLOAD"]);
const createdAt=()=>timestamp("created_at",{withTimezone:true}).notNull().defaultNow();
const updatedAt=()=>timestamp("updated_at",{withTimezone:true}).notNull().defaultNow();

export const users=pgTable("users",{id:uuid("id").primaryKey().defaultRandom(),email:text("email").notNull(),displayName:text("display_name").notNull(),passwordHash:text("password_hash").notNull(),passwordSalt:text("password_salt").notNull(),createdAt:createdAt(),updatedAt:updatedAt()},t=>[uniqueIndex("users_email_unique").on(t.email)]);
export const sessions=pgTable("sessions",{id:uuid("id").primaryKey().defaultRandom(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),createdAt:createdAt()},t=>[uniqueIndex("sessions_token_hash_unique").on(t.tokenHash),index("sessions_user_id_idx").on(t.userId)]);
export const projects=pgTable("projects",{id:uuid("id").primaryKey().defaultRandom(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),title:text("title").notNull(),description:text("description").notNull().default(""),createdAt:createdAt(),updatedAt:updatedAt()},t=>[index("projects_user_created_idx").on(t.userId,t.createdAt)]);
export const songs=pgTable("songs",{id:uuid("id").primaryKey().defaultRandom(),projectId:uuid("project_id").references(()=>projects.id,{onDelete:"set null"}),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),title:text("title").notNull(),description:text("description").notNull().default(""),lyrics:text("lyrics").notNull().default(""),isInstrumental:boolean("is_instrumental").notNull().default(false),nextVersionNumber:integer("next_version_number").notNull().default(1),archivedAt:timestamp("archived_at",{withTimezone:true}),createdAt:createdAt(),updatedAt:updatedAt()},t=>[index("songs_user_created_idx").on(t.userId,t.createdAt),index("songs_project_idx").on(t.projectId),check("songs_next_version_positive",sql`${t.nextVersionNumber}>0`)]);
export const generationJobs=pgTable("generation_jobs",{id:uuid("id").primaryKey().defaultRandom(),versionId:uuid("version_id").notNull(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),songId:uuid("song_id").notNull().references(()=>songs.id,{onDelete:"cascade"}),parentVersionId:uuid("parent_version_id"),reservedVersionNumber:integer("reserved_version_number").notNull(),idempotencyKey:text("idempotency_key").notNull(),operationType:text("operation_type").notNull().default("GENERATE"),provider:text("provider").notNull(),providerModel:text("provider_model").notNull(),status:generationStatusEnum("status").notNull().default("QUEUED"),progress:integer("progress").notNull().default(0),requestPayload:jsonb("request_payload").notNull(),compositionPlan:jsonb("composition_plan").$type<CompositionPlan>().notNull(),seed:integer("seed").notNull(),attemptCount:integer("attempt_count").notNull().default(0),maxAttempts:integer("max_attempts").notNull().default(3),lastAttemptAt:timestamp("last_attempt_at",{withTimezone:true}),nextRetryAt:timestamp("next_retry_at",{withTimezone:true}),cancellationRequestedAt:timestamp("cancellation_requested_at",{withTimezone:true}),errorCode:text("error_code"),errorMessage:text("error_message"),errorRetryable:boolean("error_retryable"),startedAt:timestamp("started_at",{withTimezone:true}),completedAt:timestamp("completed_at",{withTimezone:true}),createdAt:createdAt(),updatedAt:updatedAt()},t=>[uniqueIndex("jobs_user_idempotency_unique").on(t.userId,t.idempotencyKey),uniqueIndex("jobs_version_id_unique").on(t.versionId),index("jobs_user_status_created_idx").on(t.userId,t.status,t.createdAt),index("jobs_song_idx").on(t.songId),check("jobs_progress_range",sql`${t.progress} between 0 and 100`),check("jobs_attempts_valid",sql`${t.attemptCount}>=0 and ${t.maxAttempts}>0`)]);
export const audioAssets=pgTable("audio_assets",{id:uuid("id").primaryKey(),ownerId:uuid("owner_id").notNull().references(()=>users.id,{onDelete:"cascade"}),generationJobId:uuid("generation_job_id").references(()=>generationJobs.id,{onDelete:"set null"}),storageKey:text("storage_key").notNull(),mimeType:text("mime_type").notNull(),codec:text("codec").notNull(),sampleRate:integer("sample_rate").notNull(),bitDepth:integer("bit_depth").notNull(),channels:integer("channels").notNull(),durationSeconds:doublePrecision("duration_seconds").notNull(),fileSize:integer("file_size").notNull(),checksum:text("checksum").notNull(),waveformData:jsonb("waveform_data").$type<number[]>().notNull(),analysisMetadata:jsonb("analysis_metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:createdAt()},t=>[uniqueIndex("audio_storage_key_unique").on(t.storageKey),uniqueIndex("audio_job_checksum_unique").on(t.generationJobId,t.checksum),index("audio_owner_idx").on(t.ownerId),index("audio_generation_job_idx").on(t.generationJobId)]);
export const songVersions=pgTable("song_versions",{id:uuid("id").primaryKey(),songId:uuid("song_id").notNull().references(()=>songs.id,{onDelete:"cascade"}),parentVersionId:uuid("parent_version_id").references(():AnyPgColumn=>songVersions.id,{onDelete:"set null"}),generationJobId:uuid("generation_job_id").notNull().references(()=>generationJobs.id,{onDelete:"cascade"}),versionNumber:integer("version_number").notNull(),audioAssetId:uuid("audio_asset_id").references(()=>audioAssets.id,{onDelete:"set null"}),durationSeconds:doublePrecision("duration_seconds").notNull(),bpm:integer("bpm").notNull(),musicalKey:text("musical_key").notNull(),scale:text("scale").notNull(),lyrics:text("lyrics").notNull(),prompt:text("prompt").notNull(),stylePrompt:text("style_prompt").notNull(),compositionPlan:jsonb("composition_plan").$type<CompositionPlan>().notNull(),provider:text("provider").notNull(),providerModel:text("provider_model").notNull(),providerMetadata:jsonb("provider_metadata").$type<Record<string,unknown>>().notNull().default({}),seed:integer("seed").notNull(),createdAt:createdAt()},t=>[uniqueIndex("versions_song_number_unique").on(t.songId,t.versionNumber),uniqueIndex("versions_job_unique").on(t.generationJobId),index("versions_song_created_idx").on(t.songId,t.createdAt),index("versions_parent_idx").on(t.parentVersionId)]);
export const versionAssets=pgTable("version_assets",{id:uuid("id").primaryKey(),songVersionId:uuid("song_version_id").notNull().references(()=>songVersions.id,{onDelete:"cascade"}),audioAssetId:uuid("audio_asset_id").notNull().references(()=>audioAssets.id,{onDelete:"cascade"}),sourceAssetId:uuid("source_asset_id").references(()=>audioAssets.id,{onDelete:"restrict"}),generationMethod:trackGenerationMethodEnum("generation_method").notNull().default("FULL_SONG"),role:assetRoleEnum("role").notNull(),instrument:text("instrument"),instrumentGroup:text("instrument_group"),sourceType:provenanceEnum("source_type").notNull(),sortOrder:integer("sort_order").notNull().default(0),isPrimary:boolean("is_primary").notNull().default(false),timelineStartSeconds:doublePrecision("timeline_start_seconds").notNull().default(0),sourceStartSeconds:doublePrecision("source_start_seconds").notNull().default(0),sourceEndSeconds:doublePrecision("source_end_seconds"),gainDb:doublePrecision("gain_db").notNull().default(0),pan:doublePrecision("pan").notNull().default(0),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:createdAt()},t=>[uniqueIndex("version_assets_version_asset_unique").on(t.songVersionId,t.audioAssetId),uniqueIndex("version_assets_primary_master_unique").on(t.songVersionId,t.role).where(sql`${t.isPrimary}=true and ${t.role}='MASTER'`),index("version_assets_version_sort_idx").on(t.songVersionId,t.sortOrder),index("version_assets_role_idx").on(t.role),index("version_assets_instrument_idx").on(t.instrument),index("version_assets_source_idx").on(t.sourceAssetId),check("version_assets_pan_range",sql`${t.pan} between -1 and 1`)]);
