import { env } from "cloudflare:workers";
import { apiError, requireUser } from "../../../lib/auth";
import { compose, validateGeneration } from "../../../lib/domain";

type Row={id:string;title:string;prompt:string;createdAt:string;version:number|null;duration:number|null;bpm:number;musicalKey:string;genre:string;status:string;progress:number;seed:number;waveform:string|null;audioAssetId:string|null};
function dto(r:Row){return{id:r.id,title:r.title,prompt:r.prompt,createdAt:r.createdAt,version:r.version||1,duration:r.duration||JSON.parse(r.prompt?"12":"12"),bpm:r.bpm,musicalKey:r.musicalKey,genre:r.genre,status:r.status,progress:r.progress,seed:r.seed,waveform:r.waveform?JSON.parse(r.waveform):[],audioUrl:r.audioAssetId?`/api/audio/${r.audioAssetId}`:undefined}}
const query=`SELECT j.id,s.title,json_extract(j.request_payload,'$.prompt') prompt,j.created_at createdAt,v.version_number version,v.duration_seconds duration,json_extract(j.composition_plan,'$.bpm') bpm,json_extract(j.composition_plan,'$.key')||' '||json_extract(j.composition_plan,'$.scale') musicalKey,json_extract(j.composition_plan,'$.genre') genre,j.status,j.progress,j.seed,a.waveform_data waveform,a.id audioAssetId FROM generation_jobs j JOIN songs s ON s.id=j.song_id LEFT JOIN song_versions v ON v.generation_job_id=j.id LEFT JOIN audio_assets a ON a.id=v.audio_asset_id WHERE j.user_id=? ORDER BY j.created_at DESC LIMIT 100`;
export async function GET(request:Request){try{const user=await requireUser(request),result=await env.DB.prepare(query).bind(user.id).all<Row>();return Response.json({songs:result.results.map(dto)})}catch(error){return apiError(error)}}
export async function POST(request:Request){try{const user=await requireUser(request),input=validateGeneration(await request.json()),idempotencyKey=request.headers.get("idempotency-key")||crypto.randomUUID(),existing=await env.DB.prepare(query.replace("WHERE j.user_id=?","WHERE j.user_id=? AND j.idempotency_key=?")).bind(user.id,idempotencyKey).first<Row>();if(existing)return Response.json({song:dto(existing)},{status:200});const plan=compose(input),songId=crypto.randomUUID(),jobId=crypto.randomUUID(),seed=input.seed??Math.floor(Math.random()*2147483647),now=new Date().toISOString(),title=plan.titleSuggestions[0]||"Untitled song";await env.DB.batch([env.DB.prepare("INSERT INTO songs(id,user_id,title,description,lyrics,is_instrumental,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(songId,user.id,title,input.prompt,input.lyrics||"",input.instrumental?1:0,now,now),env.DB.prepare("INSERT INTO generation_jobs(id,user_id,song_id,idempotency_key,provider,provider_model,status,progress,request_payload,composition_plan,seed,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(jobId,user.id,songId,idempotencyKey,"mock","dozi-deterministic-wav-v1","QUEUED",4,JSON.stringify(input),JSON.stringify(plan),seed,now,now)]);return Response.json({song:{id:jobId,title,prompt:input.prompt,createdAt:now,version:1,duration:plan.durationSeconds,bpm:plan.bpm,musicalKey:`${plan.key} ${plan.scale}`,genre:plan.genre,status:"QUEUED",progress:4,seed,waveform:[]}},{status:202})}catch(error){return apiError(error)}}
