import { env } from "cloudflare:workers";
import { getSql } from "../../../db";
import { apiError, requireUser } from "../../../lib/auth";
import { compose, validateGeneration } from "../../../lib/domain";
import { CloudflareGenerationQueue, InlineTestGenerationQueue } from "../../../lib/generation-queue";
import { GenerationOrchestrator } from "../../../lib/generation-orchestrator";
import { R2AudioStorage } from "../../../lib/audio-storage";
import { createProvider } from "../../../lib/providers";
import { validateElevenLabsPolicy } from "../../../lib/provider-policy";
import type { AppBindings } from "../../../lib/config";
const bindings=env as unknown as AppBindings;
function sql(){return getSql(bindings.DATABASE_URL)}
function dto(r:Record<string,unknown>){return{id:r.id,title:r.title,prompt:r.prompt,createdAt:r.createdAt,version:r.version||1,duration:r.duration||r.planDuration,bpm:r.bpm,musicalKey:`${r.musicalKey} ${r.scale}`,genre:r.genre,provider:r.provider,status:r.status,errorMessage:r.errorMessage,progress:r.progress,seed:r.seed,waveform:r.waveform||[],audioUrl:r.audioAssetId?`/api/audio/${r.audioAssetId}`:undefined}}
const select=`select j.id,s.title,j.request_payload->>'prompt' prompt,j.created_at as "createdAt",v.version_number version,v.duration_seconds duration,(j.composition_plan->>'durationSeconds')::int as "planDuration",(j.composition_plan->>'bpm')::int bpm,j.composition_plan->>'key' as "musicalKey",j.composition_plan->>'scale' scale,j.composition_plan->>'genre' genre,j.provider,j.status,case when j.error_code='PROVIDER_PROMPT_REJECTED' then 'Prompt references restricted copyrighted or artist-identifying material.' when j.status='FAILED' then 'Generation failed.' end as "errorMessage",j.progress,j.seed,a.waveform_data waveform,a.id as "audioAssetId" from generation_jobs j join songs s on s.id=j.song_id left join song_versions v on v.generation_job_id=j.id left join audio_assets a on a.id=v.audio_asset_id`;
export async function GET(request:Request){try{const user=await requireUser(request,bindings.DATABASE_URL),database=sql(),rows=await database<Record<string,unknown>[]>`${database.unsafe(select)} where j.user_id=${user.id} order by j.created_at desc limit 100`;return Response.json({songs:rows.map(dto)})}catch(error){return apiError(error)}}
export async function POST(request:Request){try{const user=await requireUser(request,bindings.DATABASE_URL),input=validateGeneration(await request.json()),idempotencyKey=request.headers.get("idempotency-key")||crypto.randomUUID(),providerName=bindings.MUSIC_PROVIDER||"mock";if(providerName==="elevenlabs")validateElevenLabsPolicy(input);const providerConfig={aiServiceBaseUrl:bindings.AI_SERVICE_BASE_URL,aiServiceToken:bindings.AI_SERVICE_TOKEN,aceStepModel:bindings.ACESTEP_MODEL,elevenLabsApiKey:bindings.ELEVENLABS_API_KEY,elevenLabsModel:bindings.ELEVENLABS_MODEL},provider=createProvider(providerName,providerConfig),database=sql();const existing=await database<Record<string,unknown>[]>`${database.unsafe(select)} where j.user_id=${user.id} and j.idempotency_key=${idempotencyKey} limit 1`;if(existing[0])return Response.json({song:dto(existing[0])});const plan=compose(input),songId=crypto.randomUUID(),jobId=crypto.randomUUID(),versionId=crypto.randomUUID(),seed=input.seed??Math.floor(Math.random()*2147483647),title=plan.titleSuggestions[0]||"Untitled song";await database.begin(async tx=>{await tx`insert into songs(id,user_id,title,description,lyrics,is_instrumental,next_version_number) values(${songId},${user.id},${title},${input.prompt},${input.lyrics||""},${input.instrumental},2)`;await tx`insert into generation_jobs(id,version_id,user_id,song_id,reserved_version_number,idempotency_key,provider,provider_model,status,progress,request_payload,composition_plan,seed) values(${jobId},${versionId},${user.id},${songId},1,${idempotencyKey},${provider.name},${provider.model},'QUEUED',4,${tx.json(input)},${tx.json(plan)},${seed})`});const orchestrator=new GenerationOrchestrator(database,new R2AudioStorage(bindings.AUDIO),name=>createProvider(name,providerConfig)),queue=bindings.GENERATION_QUEUE?new CloudflareGenerationQueue(bindings.GENERATION_QUEUE):new InlineTestGenerationQueue(id=>orchestrator.process(id));await queue.enqueue(jobId);return Response.json({song:{id:jobId,title,prompt:input.prompt,createdAt:new Date().toISOString(),version:1,duration:plan.durationSeconds,bpm:plan.bpm,musicalKey:`${plan.key} ${plan.scale}`,genre:plan.genre,provider:provider.name,status:"QUEUED",progress:4,seed,waveform:[]}},{status:202})}catch(error){return apiError(error)}}
