import { env } from "cloudflare:workers";
import { apiError, requireUser } from "../../../../lib/auth";
import type { CompositionPlan } from "../../../../lib/domain";
import { providers } from "../../../../lib/providers";
type Job={id:string;userId:string;songId:string;title:string;status:string;progress:number;requestPayload:string;compositionPlan:string;seed:number;createdAt:string};
const selectJob="SELECT j.id,j.user_id userId,j.song_id songId,s.title,j.status,j.progress,j.request_payload requestPayload,j.composition_plan compositionPlan,j.seed,j.created_at createdAt FROM generation_jobs j JOIN songs s ON s.id=j.song_id WHERE j.id=? AND j.user_id=?";
const stages=[{after:1,status:"PREPARING",progress:18},{after:2,status:"GENERATING",progress:52},{after:4,status:"POST_PROCESSING",progress:78},{after:5,status:"UPLOADING",progress:92}];
async function complete(job:Job){const existing=await env.DB.prepare("SELECT id FROM song_versions WHERE generation_job_id=?").bind(job.id).first();if(existing)return;const plan=JSON.parse(job.compositionPlan) as CompositionPlan,request=JSON.parse(job.requestPayload) as {prompt:string;lyrics?:string},audio=await providers.mock.generate({plan,seed:job.seed}),assetId=crypto.randomUUID(),versionId=crypto.randomUUID(),key=`users/${job.userId}/masters/${assetId}.wav`,now=new Date().toISOString(),next=await env.DB.prepare("SELECT COALESCE(MAX(version_number),0)+1 n FROM song_versions WHERE song_id=?").bind(job.songId).first<{n:number}>();await env.AUDIO.put(key,audio.buffer,{httpMetadata:{contentType:"audio/wav"},customMetadata:{ownerId:job.userId,jobId:job.id,checksum:audio.checksum}});await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO audio_assets(id,owner_id,generation_job_id,storage_key,mime_type,codec,sample_rate,bit_depth,channels,duration_seconds,file_size,checksum,waveform_data,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(assetId,job.userId,job.id,key,"audio/wav","pcm_s16le",audio.sampleRate,audio.bitDepth,audio.channels,plan.durationSeconds,audio.buffer.byteLength,audio.checksum,JSON.stringify(audio.waveform),now),env.DB.prepare("INSERT OR IGNORE INTO song_versions(id,song_id,generation_job_id,version_number,audio_asset_id,duration_seconds,bpm,musical_key,scale,lyrics,prompt,style_prompt,composition_plan,provider,provider_model,seed,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(versionId,job.songId,job.id,next?.n||1,assetId,plan.durationSeconds,plan.bpm,plan.key,plan.scale,request.lyrics||"",request.prompt,plan.generationCaption,job.compositionPlan,"mock",providers.mock.model,job.seed,now),env.DB.prepare("UPDATE generation_jobs SET status='COMPLETE',progress=100,completed_at=?,updated_at=? WHERE id=? AND status!='COMPLETE'").bind(now,now,job.id)]);}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser(request),{id}=await params;let job=await env.DB.prepare(selectJob).bind(id,user.id).first<Job>();if(!job)return Response.json({error:{code:"NOT_FOUND",message:"Generation not found.",retryable:false}},{status:404});if(!["COMPLETE","FAILED","CANCELLED"].includes(job.status)){const age=(Date.now()-new Date(job.createdAt).getTime())/1000;if(age>=6)await complete(job);else{const stage=[...stages].reverse().find(s=>age>=s.after);if(stage)await env.DB.prepare("UPDATE generation_jobs SET status=?,progress=?,started_at=COALESCE(started_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(stage.status,stage.progress,id).run()}job=await env.DB.prepare(selectJob).bind(id,user.id).first<Job>() as Job}const version=await env.DB.prepare("SELECT v.version_number version,v.duration_seconds duration,a.id audioAssetId,a.waveform_data waveform FROM song_versions v JOIN audio_assets a ON a.id=v.audio_asset_id WHERE v.generation_job_id=?").bind(id).first<{version:number;duration:number;audioAssetId:string;waveform:string}>(),plan=JSON.parse(job.compositionPlan) as CompositionPlan,req=JSON.parse(job.requestPayload) as {prompt:string};return Response.json({song:{id:job.id,title:job.title,prompt:req.prompt,createdAt:job.createdAt,version:version?.version||1,duration:version?.duration||plan.durationSeconds,bpm:plan.bpm,musicalKey:`${plan.key} ${plan.scale}`,genre:plan.genre,status:job.status,progress:job.progress,seed:job.seed,waveform:version?JSON.parse(version.waveform):[],audioUrl:version?`/api/audio/${version.audioAssetId}`:undefined}})}catch(error){return apiError(error)}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser(request),{id}=await params;const result=await env.DB.prepare("UPDATE generation_jobs SET status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND status NOT IN ('COMPLETE','FAILED','CANCELLED')").bind(id,user.id).run();return Response.json({cancelled:result.meta.changes>0})}catch(error){return apiError(error)}}
